version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}

services:
 ### Caddy Server #########################################
 caddy:
   build:
     context: ./caddy
     args:
       - CADDY_DOMAIN=${DOMAIN}
       - CADDY_VERSION=${CADDY_VERSION}
   ports:
     - "${CADDY_HOST_HTTP_PORT}:80"
     - "${CADDY_HOST_HTTPS_PORT}:443"
   volumes:
     - ${DATA_PATH_HOST}:/root/.caddy
     - ${CADDY_HOST_LOG_PATH}:/var/log/caddy
     - ${SOURCE_PATH}:/var/www
   environment:
     - ACME_AGREE=true
     - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
     - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
   restart: always
   networks:
     - frontend
